modLoader="javafml"
loaderVersion="[41,)"
license="MIT License"

[[mods]]
modId="pishock"
version="1.20.1-1.0.0"
displayName="PiShock Addon"
logoFile="examplemod.png"
credits="https://pishock.com/"
authors="RaithSphere"
description='''
This Mod is for allowing pishock to be contolled from Minecraft
'''

[[dependencies.pishock]]
modId="forge"
mandatory=true
versionRange="[44,)"
ordering="NONE"
side="CLIENT"

[[dependencies.pishock]]
modId="minecraft"
mandatory=true
versionRange="[1.19,1.21)"
ordering="NONE"
side="CLIENT"